load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "DECIDE",
    srcs = ["DECIDE.java"],
    main_class = "edu.dd2480.group14.decide.program.DECIDE",
    deps = ["//src/main/java/edu/dd2480/group14/decide/core:core"],
)
