load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "DECIDE",
    srcs = ["DECIDE.java"],
    main_class = "decide.program.DECIDE",
    deps = ["//src/main/java/decide/core:core"],
)
