name: Test Application
on:
  pull_request:

jobs:
  push:
    name: Run Testsuite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount Bazel Cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install Bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Run the Testsuite
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test --curses=no --color=no -- //src/test/java/decide:testsuite
